sudo: required
services:
  - docker

before_install:
  - docker build -t bustercodes/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true bustercodes/react-test npm test

after_success:
  - docker build -t bustercodes/multi-client ./client
  - docker build -t bustercodes/multi-nginx ./nginx
  - docker build -t bustercodes/multi-server ./server
  - docker build -t bustercodes/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to Docker Hub
  - docker push bustercodes/multi-client
  - docker push bustercodes/multi-nginx
  - docker push bustercodes/multi-server
  - docker push bustercodes/multi-worker
# COURSE NOTE
# script:
#   - docker run USERNAME/react-test npm test -- --coverage
# instead should be:

# script:
#   - docker run -e CI=true USERNAME/react-test npm test
